---
# inventory file

cisco_routers:
  hosts:
    R1:
      ansible_host: 10.10.1.1
    R2:
      ansible_host: 10.10.2.2
    R3:
      ansible_host: 10.10.3.3

routers:
  children:
    cisco_routers:
